<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ckpi_tl_values;

class CkpiTlValuesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ckpi_tl_values::insert(
          array(
              [
                  "id" =>  1,
                  "tl_id" =>  1,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  55,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  2,
                  "tl_id" =>  1,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  65,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  3,
                  "tl_id" =>  1,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  4,
                  "tl_id" =>  1,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  80,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  5,
                  "tl_id" =>  1,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  90,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  6,
                  "tl_id" =>  2,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  80,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  7,
                  "tl_id" =>  2,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  95,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  8,
                  "tl_id" =>  2,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  9,
                  "tl_id" =>  2,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  100,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  10,
                  "tl_id" =>  2,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  115,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  11,
                  "tl_id" =>  3,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  18.8,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  12,
                  "tl_id" =>  3,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  15.1,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  13,
                  "tl_id" =>  3,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  14,
                  "tl_id" =>  3,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  14.3,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  15,
                  "tl_id" =>  3,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  13.7,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  16,
                  "tl_id" =>  4,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  0.89,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  17,
                  "tl_id" =>  4,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  0.72,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  18,
                  "tl_id" =>  4,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  19,
                  "tl_id" =>  4,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  0.67,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  20,
                  "tl_id" =>  4,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  0.65,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  21,
                  "tl_id" =>  5,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  0.84,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  22,
                  "tl_id" =>  5,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  0.68,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  23,
                  "tl_id" =>  5,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  24,
                  "tl_id" =>  5,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  0.63,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  25,
                  "tl_id" =>  5,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  0.61,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  26,
                  "tl_id" =>  6,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  0.46,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  27,
                  "tl_id" =>  6,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  0.38,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  28,
                  "tl_id" =>  6,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  29,
                  "tl_id" =>  6,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  0.35,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  30,
                  "tl_id" =>  6,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  0.34,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  31,
                  "tl_id" =>  7,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  1.56,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "Y",
                  "tlv_updated_count" =>  1,
                  "tlv_updated_by_name" =>  "Anis Nur Amirah Hairuman",
                  "tlv_updated_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_updated_by_date" =>  "2021-07-14 00:00:00",
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  32,
                  "tl_id" =>  7,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  1.26,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "Y",
                  "tlv_updated_count" =>  1,
                  "tlv_updated_by_name" =>  "Anis Nur Amirah Hairuman",
                  "tlv_updated_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_updated_by_date" =>  "2021-07-14 00:00:00",
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  33,
                  "tl_id" =>  7,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "Y",
                  "tlv_updated_count" =>  1,
                  "tlv_updated_by_name" =>  "Anis Nur Amirah Hairuman",
                  "tlv_updated_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_updated_by_date" =>  "2021-07-14 00:00:00",
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  34,
                  "tl_id" =>  7,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  1.19,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "Y",
                  "tlv_updated_count" =>  1,
                  "tlv_updated_by_name" =>  "Anis Nur Amirah Hairuman",
                  "tlv_updated_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_updated_by_date" =>  "2021-07-14 00:00:00",
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  35,
                  "tl_id" =>  7,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  1.14,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "Y",
                  "tlv_updated_count" =>  1,
                  "tlv_updated_by_name" =>  "Anis Nur Amirah Hairuman",
                  "tlv_updated_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_updated_by_date" =>  "2021-07-14 00:00:00",
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  36,
                  "tl_id" =>  8,
                  "tlv_rating" =>  1,
                  "tlv_value" =>  0.78,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  37,
                  "tl_id" =>  8,
                  "tlv_rating" =>  2,
                  "tlv_value" =>  0.63,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  38,
                  "tl_id" =>  8,
                  "tlv_rating" =>  3,
                  "tlv_value" =>  null,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  39,
                  "tl_id" =>  8,
                  "tlv_rating" =>  4,
                  "tlv_value" =>  0.59,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ],
                [
                  "id" =>  40,
                  "tl_id" =>  8,
                  "tlv_rating" =>  5,
                  "tlv_value" =>  0.56,
                  "tlv_description" =>  "None",
                  "tlv_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "tlv_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "tlv_created_by_date" =>  "2021-06-21 00:00:00",
                  "tlv_created_remark" =>  "",
                  "tlv_updated_status" =>  "N",
                  "tlv_updated_count" =>  0,
                  "tlv_updated_by_name" =>  "",
                  "tlv_updated_by_email" =>  "",
                  "tlv_updated_by_date" =>  null,
                  "tlv_updated_remark" =>  "",
                  "tlv_value_from" =>  "",
                  "tlv_value_to" =>  ""
                ]
          )
        );
    }
}
