<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ckpi_ils;

class CkpiIlsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ckpi_ils::insert(
          array(
              [
                  "il_id" =>  1,
                  "il_code" =>  "INDICATORCKPI000001",
                  "il_value" =>  "Portfolio Growth (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  2,
                  "il_code" =>  "INDICATORCKPI000002",
                  "il_value" =>  "Gross Impaired Ratio",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  3,
                  "il_code" =>  "INDICATORCKPI000003",
                  "il_value" =>  "Profit Before Tax and Zakat (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  4,
                  "il_code" =>  "INDICATORCKPI000004",
                  "il_value" =>  "Cost to Income Ratio",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  5,
                  "il_code" =>  "INDICATORCKPI000005",
                  "il_value" =>  "Risk Weighted Capital Ratio (RWCR)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  6,
                  "il_code" =>  "INDICATORCKPI000006",
                  "il_value" =>  "Approved Financing to Underserved (RM b)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  7,
                  "il_code" =>  "INDICATORCKPI000007",
                  "il_value" =>  "Increased in Clients Income",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  8,
                  "il_code" =>  "INDICATORCKPI000008",
                  "il_value" =>  "Additionality - Contribution to Economy",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  9,
                  "il_code" =>  "INDICATORCKPI000009",
                  "il_value" =>  "Upward Migration of Clients",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  10,
                  "il_code" =>  "INDICATORCKPI000010",
                  "il_value" =>  "Improvement in Risk Management Control Function (RMCF)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  11,
                  "il_code" =>  "INDICATORCKPI000011",
                  "il_value" =>  "Closure of CRR issues",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  12,
                  "il_code" =>  "INDICATORCKPI000012",
                  "il_value" =>  "Non-breach of Management Action Trigger (MAT) Limits",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  13,
                  "il_code" =>  "INDICATORCKPI000013",
                  "il_value" =>  "Compliance Index",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  14,
                  "il_code" =>  "INDICATORCKPI000014",
                  "il_value" =>  "Average internal audit score",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  15,
                  "il_code" =>  "INDICATORCKPI000015",
                  "il_value" =>  "Closure of Audit Issues Within the Approved Timeline",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  16,
                  "il_code" =>  "INDICATORCKPI000016",
                  "il_value" =>  "Compliance Assessment",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  17,
                  "il_code" =>  "INDICATORCKPI000017",
                  "il_value" =>  "New/Improved Process/Product/Programme",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  18,
                  "il_code" =>  "INDICATORCKPI000018",
                  "il_value" =>  "Participation in Corporate Development Programme",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  19,
                  "il_code" =>  "INDICATORCKPI000019",
                  "il_value" =>  "Company Employee Engagement Index (EEI)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  20,
                  "il_code" =>  "INDICATORCKPI000020",
                  "il_value" =>  "Retention Rate of Talent Pool",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  21,
                  "il_code" =>  "INDICATORCKPI000021",
                  "il_value" =>  "Successful Implementation of CSR Programmes (YBiz Challenge and other CSR Programmes): Satisfaction Level on Meeting the Objective of the Programme (via Survey)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "Y",
                  "il_updated_count" =>  1,
                  "il_updated_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "il_updated_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_updated_by_date" =>  "2021-07-03 00:00:00",
                  "il_updated_remark" =>  "None"
                ],
                [
                  "il_id" =>  22,
                  "il_code" =>  "INDICATORCKPI000022",
                  "il_value" =>  "Income (RM m) - Core Business",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  23,
                  "il_code" =>  "INDICATORCKPI000023",
                  "il_value" =>  "Income (RM m) - Digital Services",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  24,
                  "il_code" =>  "INDICATORCKPI000024",
                  "il_value" =>  "Profit Before Tax (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  25,
                  "il_code" =>  "INDICATORCKPI000025",
                  "il_value" =>  "Contribution to Economy : Scaling Up SMEs Growth - 5a) Companies engaged that has attained growth in sales",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  26,
                  "il_code" =>  "INDICATORCKPI000026",
                  "il_value" =>  "Contribution to Economy : Scaling Up SMEs Growth - 5b) Companies engaged that has attained increase in employment 5c) Companies engaged that has embark into digital transformation/machineries or innovation 5d) Companies engaged that are going/expanding for export market 5e) Companies engaged that has maintained staff retention 5f) Companies engaged that are going/expanding into new growth area/customer base",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  27,
                  "il_code" =>  "INDICATORCKPI000027",
                  "il_value" =>  "No. of Digital Initiative Introduced",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  28,
                  "il_code" =>  "INDICATORCKPI000028",
                  "il_value" =>  "No. of Communications and Media Outreach",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  29,
                  "il_code" =>  "INDICATORCKPI000029",
                  "il_value" =>  "No. of New/Enhanced Programmes",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  30,
                  "il_code" =>  "INDICATORCKPI000030",
                  "il_value" =>  "No. of Professional Workforce Certified",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  31,
                  "il_code" =>  "INDICATORCKPI000031",
                  "il_value" =>  "Cash Collection (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  32,
                  "il_code" =>  "INDICATORCKPI000032",
                  "il_value" =>  "Overall Reduction to NBV Amount (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  33,
                  "il_code" =>  "INDICATORCKPI000033",
                  "il_value" =>  "Profit Before Tax (PBT) (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  34,
                  "il_code" =>  "INDICATORCKPI000034",
                  "il_value" =>  "Capping of Recovery Cost (RM m)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  35,
                  "il_code" =>  "INDICATORCKPI000035",
                  "il_value" =>  "No. of Full and Final Settlement of Accounts",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  36,
                  "il_code" =>  "INDICATORCKPI000036",
                  "il_value" =>  "Successful Completion of SCI",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ],
                [
                  "il_id" =>  37,
                  "il_code" =>  "INDICATORCKPI000037",
                  "il_value" =>  "Corporate Social Responsibility (CSR)",
                  "il_description" =>  "None",
                  "il_created_by_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
                  "il_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "il_created_by_date" =>  "2021-06-21 00:00:00",
                  "il_created_remark" =>  "",
                  "il_updated_status" =>  "N",
                  "il_updated_count" =>  0,
                  "il_updated_by_name" =>  "",
                  "il_updated_by_email" =>  "",
                  "il_updated_by_date" =>  null,
                  "il_updated_remark" =>  ""
                ]
          )
        );
    }
}
