<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ckpi_perspectives;

class CkpiPerspectivesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ckpi_perspectives::insert(
          array(
              [
                  "id" =>  1,
                  "group_id" =>  1,
                  "app_id" =>  1,
                  "perspective_group" =>  "BANK CKPI",
                  "perspective_perspective" =>  "FINANCIAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  2,
                  "group_id" =>  1,
                  "app_id" =>  1,
                  "perspective_group" =>  "BANK CKPI",
                  "perspective_perspective" =>  "DEVELOPMENTAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  3,
                  "group_id" =>  1,
                  "app_id" =>  1,
                  "perspective_group" =>  "BANK CKPI",
                  "perspective_perspective" =>  "INTERNAL BUSINESS PROCESS",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  4,
                  "group_id" =>  1,
                  "app_id" =>  1,
                  "perspective_group" =>  "BANK CKPI",
                  "perspective_perspective" =>  "INNOVATION AND LEARNING",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  5,
                  "group_id" =>  1,
                  "app_id" =>  1,
                  "perspective_group" =>  "BANK CKPI",
                  "perspective_perspective" =>  "STAFF SATISFACTION",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  6,
                  "group_id" =>  1,
                  "app_id" =>  1,
                  "perspective_group" =>  "BANK CKPI",
                  "perspective_perspective" =>  "ENVIRONMENT AND COMMUNITY",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  7,
                  "group_id" =>  2,
                  "app_id" =>  1,
                  "perspective_group" =>  "GROUP CKPI",
                  "perspective_perspective" =>  "FINANCIAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  8,
                  "group_id" =>  2,
                  "app_id" =>  1,
                  "perspective_group" =>  "GROUP CKPI",
                  "perspective_perspective" =>  "DEVELOPMENTAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  9,
                  "group_id" =>  2,
                  "app_id" =>  1,
                  "perspective_group" =>  "GROUP CKPI",
                  "perspective_perspective" =>  "INTERNAL BUSINESS PROCESS",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  10,
                  "group_id" =>  2,
                  "app_id" =>  1,
                  "perspective_group" =>  "GROUP CKPI",
                  "perspective_perspective" =>  "INNOVATION AND LEARNING",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  11,
                  "group_id" =>  2,
                  "app_id" =>  1,
                  "perspective_group" =>  "GROUP CKPI",
                  "perspective_perspective" =>  "STAFF SATISFACTION",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  12,
                  "group_id" =>  2,
                  "app_id" =>  1,
                  "perspective_group" =>  "GROUP CKPI",
                  "perspective_perspective" =>  "ENVIRONMENT AND COMMUNITY",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  13,
                  "group_id" =>  3,
                  "app_id" =>  1,
                  "perspective_group" =>  "CEDAR CKPI",
                  "perspective_perspective" =>  "FINANCIAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  14,
                  "group_id" =>  3,
                  "app_id" =>  1,
                  "perspective_group" =>  "CEDAR CKPI",
                  "perspective_perspective" =>  "DEVELOPMENTAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  15,
                  "group_id" =>  3,
                  "app_id" =>  1,
                  "perspective_group" =>  "CEDAR CKPI",
                  "perspective_perspective" =>  "INTERNAL BUSINESS PROCESS",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  16,
                  "group_id" =>  3,
                  "app_id" =>  1,
                  "perspective_group" =>  "CEDAR CKPI",
                  "perspective_perspective" =>  "INNOVATION AND LEARNING",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  19,
                  "group_id" =>  4,
                  "app_id" =>  1,
                  "perspective_group" =>  "SAM CKPI",
                  "perspective_perspective" =>  "FINANCIAL",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  21,
                  "group_id" =>  4,
                  "app_id" =>  1,
                  "perspective_group" =>  "SAM CKPI",
                  "perspective_perspective" =>  "INTERNAL BUSINESS PROCESS",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  22,
                  "group_id" =>  4,
                  "app_id" =>  1,
                  "perspective_group" =>  "SAM CKPI",
                  "perspective_perspective" =>  "INNOVATION AND LEARNING",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ],
                [
                  "id" =>  24,
                  "group_id" =>  4,
                  "app_id" =>  1,
                  "perspective_group" =>  "SAM CKPI",
                  "perspective_perspective" =>  "ENVIRONMENT AND COMMUNITY",
                  "perspective_created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
                  "perspective_created_by_email" =>  "anis.hairuman@smebank.com.my",
                  "perspective_created_by_date" =>  "2021-07-03 00:00:00",
                  "perspective_created_remark" =>  "created via create list application",
                  "perspective_updated_status" =>  "N",
                  "perspective_updated_count" =>  0,
                  "perspective_updated_by_name" =>  "",
                  "perspective_updated_by_email" =>  "",
                  "perspective_updated_by_date" =>  null,
                  "perspective_updated_remark" =>  ""
                ]
          )
        );
    }
}
