<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Users;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       Users::insert(
         array(
        [
            "user_id" =>  1,
            "pw" =>  1234,
            "staff_name" =>  "ROZAIMI BIN ZAMAHRI",
            "email_address" =>  "rozaimi.zamahri@smebank.com.my",
            "ext_no" =>  0,
            "token_jwt" =>  "",
            "level_access" =>  "SUPERADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  1,
            "active" =>  "Y",
            "last_login" =>  "2021-08-05 00:00:00",
            "last_logout" =>  "2021-07-08 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-01-06 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  2,
            "pw" =>  1234,
            "staff_name" =>  "KHAIRUL FAIZAL BIN ARIFFIN",
            "email_address" =>  "khairul.faizal@smebank.com.my",
            "ext_no" =>  60326152108,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "OBP",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  "2021-06-21 00:00:00",
            "last_logout" =>  "2021-01-06 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-01-06 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  3,
            "pw" =>  1234,
            "staff_name" =>  "HASNULAZMA BINTI YAAKUB",
            "email_address" =>  "hasnulazma@smebank.com.my",
            "ext_no" =>  60326152108,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "OBP",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  "2021-06-21 00:00:00",
            "last_logout" =>  "2021-01-06 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-01-06 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  4,
            "pw" =>  1234,
            "staff_name" =>  "MOHD HUZAIMI BIN HASHIM",
            "email_address" =>  "mohd.huzaimi@smebank.com.my",
            "ext_no" =>  60326152108,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "OBP",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  "2021-06-21 00:00:00",
            "last_logout" =>  "2021-01-06 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-01-06 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  5,
            "pw" =>  null,
            "staff_name" =>  "ANIS NUR AMIRAH BINTI HAIRUMAN",
            "email_address" =>  "anis.hairuman@smebank.com.my",
            "ext_no" =>  0,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  1,
            "active" =>  "Y",
            "last_login" =>  "2021-07-30 00:00:00",
            "last_logout" =>  "2021-07-21 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-04 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  6,
            "pw" =>  null,
            "staff_name" =>  "RAIHAN AIDA BINTI ISMAIL",
            "email_address" =>  "raihan@smebank.com.my",
            "ext_no" =>  0,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  2,
            "active" =>  "Y",
            "last_login" =>  "2021-08-16 00:00:00",
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-04 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  7,
            "pw" =>  null,
            "staff_name" =>  "AZLAN BIN SHAHARUDDIN",
            "email_address" =>  "azlan@smebank.com.my",
            "ext_no" =>  null,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  3,
            "active" =>  "Y",
            "last_login" =>  "2021-06-21 00:00:00",
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-04 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  8,
            "pw" =>  null,
            "staff_name" =>  "ZURINA BINTI OMAR",
            "email_address" =>  "zurina@smebank.com.my",
            "ext_no" =>  60326152979,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "OBP",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  "2021-07-08 00:00:00",
            "last_logout" =>  "2021-07-08 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-10 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  9,
            "pw" =>  null,
            "staff_name" =>  "MUHAMMAD RASHDAN BIN KAMARUDDIN",
            "email_address" =>  "muhammad.rashdan@smebank.com.my",
            "ext_no" =>  0,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "OBP",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  "2021-07-22 00:00:00",
            "last_logout" =>  "2021-07-19 00:00:00",
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-10 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  10,
            "pw" =>  null,
            "staff_name" =>  "YUSRI NABIHAH BINTI MOHD YAZID",
            "email_address" =>  "yusri_nabihah@smebank.com.my",
            "ext_no" =>  0,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  1,
            "active" =>  "Y",
            "last_login" =>  "2021-07-15 00:00:00",
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-31 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  11,
            "pw" =>  null,
            "staff_name" =>  "MOHAMAD SUFIAN BIN SUBANDZI",
            "email_address" =>  "mohamad.sufian@smebank.com.my",
            "ext_no" =>  null,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  1,
            "active" =>  "Y",
            "last_login" =>  "2021-06-21 00:00:00",
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-05-31 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  12,
            "pw" =>  null,
            "staff_name" =>  "MOHD ZUHRI BIN MOHD SUKRI",
            "email_address" =>  "zuhri@smebank.com.my",
            "ext_no" =>  null,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  1,
            "active" =>  "Y",
            "last_login" =>  null,
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI BIN ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-06-03 00:00:00",
            "created_remark" =>  "",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  13,
            "pw" =>  null,
            "staff_name" =>  "PENTEST ASK1",
            "email_address" =>  "askuser@smebank.com.my",
            "ext_no" =>  null,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "OBP",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  null,
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-06-24 00:00:00",
            "created_remark" =>  "Created via system",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  14,
            "pw" =>  null,
            "staff_name" =>  "NUR IMAN NAZIRAH BINTI NASIR",
            "email_address" =>  "nazirah@smebank.com.my",
            "ext_no" =>  null,
            "token_jwt" =>  "",
            "level_access" =>  "SUPERADMIN",
            "module_access" =>  "",
            "approver_access" =>  null,
            "active" =>  "Y",
            "last_login" =>  null,
            "last_logout" =>  null,
            "created_by_name" =>  "ROZAIMI ZAMAHRI",
            "created_by_email" =>  "rozaimi.zamahri@smebank.com.my",
            "created_by_date" =>  "2021-06-29 00:00:00",
            "created_remark" =>  "Created via system",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ],
          [
            "user_id" =>  15,
            "pw" =>  null,
            "staff_name" =>  "SHAORIN SALAWATI SHAM BINTI SHAM MOHAMED",
            "email_address" =>  "shaorin@smebank.com.my",
            "ext_no" =>  0,
            "token_jwt" =>  "",
            "level_access" =>  "ADMIN",
            "module_access" =>  "CKPI",
            "approver_access" =>  1,
            "active" =>  "Y",
            "last_login" =>  "2021-07-14 00:00:00",
            "last_logout" =>  "2021-07-14 00:00:00",
            "created_by_name" =>  "ANIS NUR AMIRAH HAIRUMAN",
            "created_by_email" =>  "anis.hairuman@smebank.com.my",
            "created_by_date" =>  "2021-07-12 00:00:00",
            "created_remark" =>  "Created via system",
            "updated_status" =>  "N",
            "updated_count" =>  0,
            "updated_by_name" =>  "",
            "updated_by_email" =>  "",
            "updated_by_date" =>  null,
            "updated_remark" =>  ""
          ]
         )
        );
    }
}
